export interface DefaultProductItem {
  sku: string;
  name: string;
  category: string;
  type: "PRODUCT" | "SERVICE";
  price: number;
  cost: number;
  inventory: number;
  unit: string;
  description: string;
  location?: string;
}

export const INVENTORY_CATALOG: DefaultProductItem[] = [
  // 5.2 mm European Collection Lite
  {
    sku: "F01",
    name: "F01 - Austria",
    category: "5.2 mm European Collection Lite",
    type: "PRODUCT",
    price: 1.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.2 mm European Collection Lite | Type: SPC | Size: 9\"X48\"X 5.2mm | UL: 1.5mm | Wear Layer: 18mil | Bx/Plt: 56 | Sqft/Bx: 30.18 sqft | Price: $1.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "F02",
    name: "F02 - Hungary",
    category: "5.2 mm European Collection Lite",
    type: "PRODUCT",
    price: 1.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.2 mm European Collection Lite | Type: SPC | Size: 9\"X48\"X 5.2mm | UL: 1.5mm | Wear Layer: 18mil | Bx/Plt: 56 | Sqft/Bx: 30.18 sqft | Price: $1.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "F03",
    name: "F03 - Norway",
    category: "5.2 mm European Collection Lite",
    type: "PRODUCT",
    price: 1.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.2 mm European Collection Lite | Type: SPC | Size: 9\"X48\"X 5.2mm | UL: 1.5mm | Wear Layer: 18mil | Bx/Plt: 56 | Sqft/Bx: 30.19 sqft | Price: $1.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "F04",
    name: "F04 - Sweden",
    category: "5.2 mm European Collection Lite",
    type: "PRODUCT",
    price: 1.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.2 mm European Collection Lite | Type: SPC | Size: 9\"X48\"X 5.2mm | UL: 1.5mm | Wear Layer: 18mil | Bx/Plt: 56 | Sqft/Bx: 30.20 sqft | Price: $1.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "F05",
    name: "F05 - Turkey",
    category: "5.2 mm European Collection Lite",
    type: "PRODUCT",
    price: 1.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.2 mm European Collection Lite | Type: SPC | Size: 9\"X48\"X 5.2mm | UL: 1.5mm | Wear Layer: 18mil | Bx/Plt: 56 | Sqft/Bx: 30.21 sqft | Price: $1.49/sqft",
    location: "Houston Warehouse",
  },

  // 6.0 mm European Collection Plus
  {
    sku: "J01",
    name: "J01 - England",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J02",
    name: "J02 - Ireland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J03",
    name: "J03 - Scotland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J04",
    name: "J04 - Poland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J05",
    name: "J05 - Greenland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J06",
    name: "J06 - Iceland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J07",
    name: "J07 - Finland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J08",
    name: "J08 - Newfoundland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J09",
    name: "J09 - Lapland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "J10",
    name: "J10 - Zeeland",
    category: "6.0 mm European Collection Plus",
    type: "PRODUCT",
    price: 1.79,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0 mm European Collection Plus | Type: SPC | Size: 9\"X48\"X 6.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 30.18 sqft | Price: $1.79/sqft",
    location: "Houston Warehouse",
  },

  // 5.5 mm U.S.A Collection
  {
    sku: "D01",
    name: "D01 - Irvine",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D02",
    name: "D02 - Boston",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D03",
    name: "D03 - Orlando",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D04",
    name: "D04 - Seattle",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D05",
    name: "D05 - Houston",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D06",
    name: "D06 - Chicago",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D07",
    name: "D07 - Portland",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D08",
    name: "D08 - Phoenix",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D09",
    name: "D09 - Denver",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "D10",
    name: "D10 - Napa",
    category: "5.5 mm U.S.A Collection",
    type: "PRODUCT",
    price: 1.69,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 5.5 mm U.S.A Collection | Type: SPC | Size: 9\"X60\"X 5.5mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Box: 30.18 sqft | Price: $1.69/sqft",
    location: "Houston Warehouse",
  },

  // 6.0mm European Collection
  {
    sku: "A01",
    name: "A01 - Germany",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A02",
    name: "A02 - Britain",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A03",
    name: "A03 - France",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A04",
    name: "A04 - Denmark",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A05",
    name: "A05 - Spain",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A06",
    name: "A06 - Italy",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A07",
    name: "A07 - Belgium",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A08",
    name: "A08 - Netherlands",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A09",
    name: "A09 - Greece",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "A10",
    name: "A10 - Switzerland",
    category: "6.0mm European Collection",
    type: "PRODUCT",
    price: 1.89,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 6.0mm European Collection | Type: SPC | Size: 9\"X60\"X 6.0mm | UL: 1.5mm | Wear Layer: 20mil | Bx/Plt: 44 | Sqft/Box: 30.18 sqft | Price: $1.89/sqft",
    location: "Houston Warehouse",
  },

  // 12.0 mm Global Collection (WaterProof Laminate)
  {
    sku: "L1211",
    name: "L1211 - New York",
    category: "12.0 mm Global Collection (WaterProof Laminate)",
    type: "PRODUCT",
    price: 1.99,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm Global Collection (WaterProof Laminate) | Type: Laminate | Size: 9.37\"X48\"X 12mm | Thickness: 12mm | Wear Layer: AC4 | Bx/Plt: 52 | Sqft/Box: 18.74 sqft | Price: $1.99/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1212",
    name: "L1212 - Austin",
    category: "12.0 mm Global Collection (WaterProof Laminate)",
    type: "PRODUCT",
    price: 1.99,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm Global Collection (WaterProof Laminate) | Type: Laminate | Size: 9.37\"X48\"X 12mm | Thickness: 12mm | Wear Layer: AC4 | Bx/Plt: 52 | Sqft/Box: 18.74 sqft | Price: $1.99/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1213",
    name: "L1213 - Beijing",
    category: "12.0 mm Global Collection (WaterProof Laminate)",
    type: "PRODUCT",
    price: 1.99,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm Global Collection (WaterProof Laminate) | Type: Laminate | Size: 9.37\"X48\"X 12mm | Thickness: 12mm | Wear Layer: AC4 | Bx/Plt: 52 | Sqft/Box: 18.74 sqft | Price: $1.99/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1214",
    name: "L1214 - Lodon",
    category: "12.0 mm Global Collection (WaterProof Laminate)",
    type: "PRODUCT",
    price: 1.99,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm Global Collection (WaterProof Laminate) | Type: Laminate | Size: 9.37\"X48\"X 12mm | Thickness: 12mm | Wear Layer: AC4 | Bx/Plt: 52 | Sqft/Box: 18.74 sqft | Price: $1.99/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1215",
    name: "L1215 - Paris",
    category: "12.0 mm Global Collection (WaterProof Laminate)",
    type: "PRODUCT",
    price: 1.99,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm Global Collection (WaterProof Laminate) | Type: Laminate | Size: 9.37\"X48\"X 12mm | Thickness: 12mm | Wear Layer: AC4 | Bx/Plt: 52 | Sqft/Box: 18.74 sqft | Price: $1.99/sqft",
    location: "Houston Warehouse",
  },

  // 7.0 mm U.S. Park Collection
  {
    sku: "P01",
    name: "P01 - Central Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P02",
    name: "P02 - Golden State Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P03",
    name: "P03 - Prospect Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P04",
    name: "P04 - Liberty Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P05",
    name: "P05 - Griffith Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P06",
    name: "P06 - Discovery Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P07",
    name: "P07 - Jackson Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P08",
    name: "P08 - Lincoln Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P09",
    name: "P09 - Fairmount Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "P10",
    name: "P10 - Grant Park",
    category: "7.0 mm U.S. Park Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 7.0 mm U.S. Park Collection | Type: SPC | Size: 9\"X60\"X 7.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 48 | Sqft/Bx: 22.72 sqft | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },

  // 8.0 mm U.S. River Collection
  {
    sku: "C06",
    name: "C06 - Columbia River",
    category: "8.0 mm U.S. River Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm U.S. River Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Bx: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "C07",
    name: "C07 - Yukon River",
    category: "8.0 mm U.S. River Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm U.S. River Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Bx: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "C08",
    name: "C08 - Hudson River",
    category: "8.0 mm U.S. River Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm U.S. River Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Bx: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "C09",
    name: "C09 - Arkansas River",
    category: "8.0 mm U.S. River Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm U.S. River Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Bx: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "C10",
    name: "C10 - Tennessee River",
    category: "8.0 mm U.S. River Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm U.S. River Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Bx: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },

  // 8.0 mm Global Collection
  {
    sku: "C01",
    name: "C01 - Tokyo",
    category: "8.0 mm Global Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm Global Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Box: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "C02",
    name: "C02 - Dubai",
    category: "8.0 mm Global Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm Global Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Box: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "C03",
    name: "C03 - Sydney",
    category: "8.0 mm Global Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm Global Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Box: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "C04",
    name: "C04 - Toronto",
    category: "8.0 mm Global Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm Global Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Box: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "C05",
    name: "C05 - Vienna",
    category: "8.0 mm Global Collection",
    type: "PRODUCT",
    price: 2.49,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 8.0 mm Global Collection | Type: SPC | Size: 9\"X60\"X 8.0mm | UL: 2.0mm | Wear Layer: 20mil | Bx/Plt: 40 | Sqft/Box: 22.72 sqft | Price: $2.49/sqft",
    location: "Houston Warehouse",
  },

  // 12.0 mm U.S. Laker Collection
  {
    sku: "L1201",
    name: "L1201 - South Africa",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1202",
    name: "L1202 - Guinea",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1203",
    name: "L1203 - Nigeria",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1204",
    name: "L1204 - Uganda",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1205",
    name: "L1205 - Tunisia",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1206",
    name: "L1206 - Tanzania",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1207",
    name: "L1207 - Liberia",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1208",
    name: "L1208 - Madagascar",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1209",
    name: "L1209 - Mauritius",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },
  {
    sku: "L1210",
    name: "L1210 - Morocco",
    category: "12.0 mm U.S. Laker Collection",
    type: "PRODUCT",
    price: 2.19,
    cost: 0,
    inventory: 100000,
    unit: "sqft",
    description: "Collection: 12.0 mm U.S. Laker Collection | Type: Laminate | Size: 7-3/4\"X48\"X(10+2)mm | Wear Layer: AC4 | Bx/Plt: 50 | Sqft/Bx: 20.92 sqft | Weight: 50LB/BOX | Price: $2.19/sqft",
    location: "Houston Warehouse",
  },

  // Moldings & Accessories
  {
    sku: "MOLD-FSN",
    name: "MOLD-FSN - Flush Stair Nose",
    category: "Moldings",
    type: "PRODUCT",
    price: 35.0,
    cost: 0,
    inventory: 100000,
    unit: "stick",
    description: "Category: Moldings | Item: Flush Stair Nose | Size: 8 feet/Stick | Compatible with 5.2/5.5/6.0/6.5/7.0/8.0/10.0 mm SPC & Laminate | Price: $35.00/stick",
    location: "Houston Warehouse",
  },
  {
    sku: "MOLD-TM",
    name: "MOLD-TM - T-Molding",
    category: "Moldings",
    type: "PRODUCT",
    price: 25.0,
    cost: 0,
    inventory: 100000,
    unit: "stick",
    description: "Category: Moldings | Item: T-Molding | Size: 8 feet/Stick | Compatible with 5.2/5.5/6.0/6.5/7.0/8.0/10.0 mm SPC & Laminate | Price: $25.00/stick",
    location: "Houston Warehouse",
  },
  {
    sku: "MOLD-RED",
    name: "MOLD-RED - Reducer",
    category: "Moldings",
    type: "PRODUCT",
    price: 25.0,
    cost: 0,
    inventory: 100000,
    unit: "stick",
    description: "Category: Moldings | Item: Reducer | Size: 8 feet/Stick | Compatible with 5.2/5.5/6.0/6.5/7.0/8.0/10.0 mm SPC & Laminate | Price: $25.00/stick",
    location: "Houston Warehouse",
  },
  {
    sku: "MOLD-QR",
    name: "MOLD-QR - Quarter Round (Match color)",
    category: "Moldings",
    type: "PRODUCT",
    price: 20.0,
    cost: 0,
    inventory: 100000,
    unit: "stick",
    description: "Category: Moldings | Item: Quarter Round (Match color) | Size: 8 feet/Stick | Match color | Compatible with 5.2/5.5/6.0/6.5/7.0/8.0/10.0 mm SPC & Laminate | Price: $20.00/stick",
    location: "Houston Warehouse",
  },
  {
    sku: "MOLD-MDF-QR",
    name: "MOLD-MDF-QR - MDF Quarter Round (White)",
    category: "Moldings",
    type: "PRODUCT",
    price: 8.0,
    cost: 0,
    inventory: 100000,
    unit: "stick",
    description: "Category: Moldings | Item: MDF Quarter Round (White) | Size: 8 feet/Stick | Color: White | Price: $8.00/stick",
    location: "Houston Warehouse",
  },
  {
    sku: "ACC-MB-6MIL",
    name: "ACC-MB-6MIL - Moisture Barrier PE Film (6mil)",
    category: "Accessories",
    type: "PRODUCT",
    price: 49.0,
    cost: 0,
    inventory: 100000,
    unit: "roll",
    description: "Category: Accessories | Item: Moisture Barrier PE Film (6mil) | Size: 500 sqft/Roll | Thickness: 6mil | Price: $49.00/roll",
    location: "Houston Warehouse",
  },
  {
    sku: "ACC-EVA-3MM",
    name: "ACC-EVA-3MM - Premium Floor EVA Underlayment (3.0mm)",
    category: "Accessories",
    type: "PRODUCT",
    price: 49.0,
    cost: 0,
    inventory: 100000,
    unit: "roll",
    description: "Category: Accessories | Item: Premium Floor EVA Underlayment (3.0mm) | Size: 200 sqft/Roll | Thickness: 3.0mm | Price: $49.00/roll",
    location: "Houston Warehouse",
  },
];
